const TOOLS = [
  {
    id: "kubernetes",
    name: "Kubernetes",
    tagline: "Automated container deployment, scaling, and operational management at planet scale.",
    category: "Container & Orchestration",
    status: "CNCF Graduated",
    license: "Apache 2.0",
    stars: "110,000+",
    website: "https://kubernetes.io",
    github: "https://github.com/kubernetes/kubernetes",
    icon: "/img/icons/kubernetes.svg",
    tags: ["containers", "orchestration", "cloud-native", "cncf-graduated", "scaling", "cluster"],
    whatItDoes: "Kubernetes (often abbreviated K8s) is an open-source container orchestration system that automates the deployment, scaling, healing, and management of containerized workloads. Originally designed by Google and maintained by the Cloud Native Computing Foundation (CNCF), it abstracts physical or virtual machines into a unified cluster of compute resources.",
    whyItsUsed: "Before Kubernetes, teams manually managed VMs, wrote custom restart scripts, and struggled to scale microservices during traffic spikes. Kubernetes eliminates infrastructure lock-in, enabling applications to run identically on AWS, Azure, Google Cloud, or on-premise hardware. It provides declarative configuration, automatic rollouts/rollbacks, intelligent scheduling, self-healing container restarts, and automated service discovery.",
    architecture: "Kubernetes consists of a Control Plane and Worker Nodes. The Control Plane includes the API Server (the front-end REST interface), etcd (a consistent distributed key-value store holding the entire cluster state), Kube-Scheduler (assigns newly created pods to optimal nodes), and Kube-Controller-Manager (runs background reconciliation loops). Each Worker Node runs Kubelet (node agent communicating with the API server), Kube-proxy (network proxy managing Service IP routing), and an OCI-compliant Container Runtime (such as containerd).",
    keyFeatures: [
      "Declarative Desired State: Declare how many replicas and resources you want; K8s continuously reconciles reality to match.",
      "Automated Self-Healing: Automatically restarts failed containers, replaces unhealthy nodes, and reschedules evicted pods.",
      "Horizontal Pod Autoscaling (HPA): Dynamically scales pod replicas up or down based on CPU, memory, or custom metrics.",
      "Automated Rollouts & Rollbacks: Safely rolls out changes one pod at a time and rolls back instantly if health checks fail.",
      "Storage & Secret Orchestration: Dynamically mounts persistent disks (EBS, PersistentVolumes) and injects encrypted secrets without rebuilding images."
    ],
    quickstart: "# Start a local Kubernetes cluster using minikube\nminikube start\n\n# Deploy a sample web service\nkubectl create deployment web --image=nginx:alpine\nkubectl expose deployment web --type=NodePort --port=80\n\n# Verify pods and endpoints\nkubectl get pods,services",
    whenToUse: "Ideal for organizations migrating to microservices, running distributed applications that require high availability, or building an internal developer platform. May be overkill for single monolithic apps or very small teams with minimal operational capacity."
  },
  {
    id: "docker",
    name: "Docker",
    tagline: "The foundational open standard for packaging, distributing, and running containerized apps.",
    category: "Containerization",
    status: "Open Source Standard",
    license: "Apache 2.0",
    stars: "69,000+",
    website: "https://www.docker.com",
    github: "https://github.com/moby/moby",
    icon: "/img/icons/docker.svg",
    tags: ["containers", "docker", "packaging", "linux", "runtime", "oci"],
    whatItDoes: "Docker revolutionised software engineering by popularising OS-level virtualization through lightweight containers. A Docker container packages code, runtime, system tools, and libraries together, guaranteeing that software executes identically regardless of the underlying host operating system.",
    whyItsUsed: "Solves the notorious 'it works on my machine' bug once and for all. By separating applications from the underlying infrastructure, Docker allows developers to write code locally in reproducible environments, ship immutable images through CI/CD pipelines, and deploy directly to production with zero environment configuration drift.",
    architecture: "Docker uses a client-server architecture. The Docker CLI issues commands over a REST API or UNIX socket to the Docker Daemon (dockerd). The daemon manages Docker objects (images, containers, networks, volumes) and delegates execution to containerd and runc, leveraging Linux kernel namespaces (for isolation) and cgroups (for resource limits).",
    keyFeatures: [
      "Immutable OCI Image Artifacts: Multi-stage Dockerfiles create minimal, reproducible container images.",
      "Lightweight Process Isolation: Containers share the host OS kernel, starting in milliseconds with tiny resource overhead compared to heavy VMs.",
      "Docker Compose: Define and run complex multi-container local applications using a single declarative YAML file.",
      "Vast Ecosystem: Access to hundreds of thousands of official, audited open-source base images on Docker Hub and GitHub Container Registry."
    ],
    quickstart: "# Build and run an interactive container locally\ndocker run -d --name web -p 8080:80 nginx:alpine\n\n# Inspect running containers\ndocker ps\n\n# Open terminal inside the container\ndocker exec -it web sh",
    whenToUse: "Essential for virtually every modern developer and DevOps workflow. Use it to containerize applications, construct deterministic CI build steps, and orchestrate local development stacks."
  },
  {
    id: "opentofu",
    name: "OpenTofu / Terraform",
    tagline: "Declarative Infrastructure as Code (IaC) to provision cloud resources reliably and repeatably.",
    category: "Infrastructure as Code",
    status: "Linux Foundation",
    license: "MPL 2.0",
    stars: "23,000+",
    website: "https://opentofu.org",
    github: "https://github.com/opentofu/opentofu",
    icon: "/img/icons/opentofu.svg",
    tags: ["iac", "opentofu", "terraform", "cloud-automation", "multi-cloud", "hcl"],
    whatItDoes: "OpenTofu is an openly governed, community-driven fork of Terraform under the Linux Foundation. It allows platform and DevOps engineers to define complete multi-cloud infrastructure—virtual machines, VPCs, Kubernetes clusters, IAM policies, and databases—in human-readable declarative HashiCorp Configuration Language (HCL).",
    whyItsUsed: "Manual cloud console clicking is slow, error-prone, and cannot be audited. OpenTofu brings software engineering best practices to infrastructure: version control, code reviews, automated CI testing, and deterministic deployments. Its two-step 'plan' and 'apply' workflow lets engineers preview every change before applying it to production clouds.",
    architecture: "OpenTofu reads configuration files (`.tf`), constructs a directed acyclic graph (DAG) of all declared resources, and compares desired state against the current state file (`tofu.tfstate`). It then dynamically calls provider plugins via gRPC (e.g. AWS, Azure, Google Cloud, Cloudflare) to execute only the necessary create, update, or destroy operations.",
    keyFeatures: [
      "Provider Ecosystem: Thousands of plug-and-play providers supporting every major cloud and SaaS API.",
      "Safe Execution Planning: `tofu plan` displays exact additions, in-place updates, and destructive replacements before any change touches live cloud resources.",
      "State Management: Tracks real-world resource mappings and attributes with remote locking backends (S3, GCS, Consul) for team collaboration.",
      "Reusable Modular Architecture: Create parameterized infrastructure modules for standard VPCs, EKS/AKS clusters, and database tiers."
    ],
    quickstart: "# Initialize directory and install required cloud providers\ntofu init\n\n# Generate and review the execution plan\ntofu plan\n\n# Apply changes to provision infrastructure\ntofu apply",
    whenToUse: "The industry standard for provisioning static and semi-static cloud infrastructure across multi-cloud and hybrid environments."
  },
  {
    id: "ansible",
    name: "Ansible",
    tagline: "Simple, agentless IT automation, configuration management, and application deployment.",
    category: "Configuration Management",
    status: "Red Hat / Open Source",
    license: "GPL 3.0",
    stars: "62,000+",
    website: "https://www.ansible.com",
    github: "https://github.com/ansible/ansible",
    icon: "/img/icons/ansible.svg",
    tags: ["configuration-management", "automation", "agentless", "ssh", "playbooks", "linux"],
    whatItDoes: "Ansible is an open-source configuration management, orchestration, and automation tool created to automate repetitive sysadmin tasks. It configures servers, installs packages, manages security baselines, and orchestrates rolling updates across fleets of bare-metal machines, virtual servers, and network devices.",
    whyItsUsed: "Unlike older configuration management tools (such as Puppet or Chef), Ansible is completely agentless. It requires no daemon or background process installed on managed nodes; it connects over standard SSH (or WinRM on Windows) and executes Python modules. Its playbooks are written in simple YAML, making them accessible to sysadmins, developers, and security auditors alike.",
    architecture: "Ansible runs from a single control machine. It reads an inventory file listing target hosts and host groups. When executing a playbook, Ansible parses the YAML tasks, generates optimized Python execution scripts, copies them temporarily to the remote targets over SSH, executes them, returns JSON results, and removes the temporary scripts.",
    keyFeatures: [
      "Agentless Architecture: Zero client software to install, patch, or keep running on target systems.",
      "Idempotent Execution: Tasks only make changes if the system is not already in the declared target state.",
      "Human-Readable Playbooks: Express complex workflows cleanly in YAML with conditional logic, loops, and variable interpolation.",
      "Ansible Galaxy: A massive open registry of community and vendor-certified roles and collections."
    ],
    quickstart: "# Ad-hoc ping test across all inventory hosts\nansible all -i inventory.ini -m ping\n\n# Execute a configuration playbook\nansible-playbook -i inventory.ini deploy-webserver.yml",
    whenToUse: "Perfect for configuring OS layers, provisioning VMs, patching fleets of Linux/Windows servers, automating network switches, and orchestrating deployment sequences across multiple tiers."
  },
  {
    id: "argocd",
    name: "Argo CD",
    tagline: "Declarative, continuous delivery GitOps operator for Kubernetes.",
    category: "CI/CD & GitOps",
    status: "CNCF Graduated",
    license: "Apache 2.0",
    stars: "17,000+",
    website: "https://argo-cd.readthedocs.io",
    github: "https://github.com/argoproj/argo-cd",
    icon: "/img/icons/argocd.svg",
    tags: ["gitops", "continuous-delivery", "kubernetes", "cncf-graduated", "argocd", "automation"],
    whatItDoes: "Argo CD is a declarative GitOps continuous delivery tool for Kubernetes. It implements the GitOps principle: Git repositories serve as the single source of truth for the desired state of infrastructure and applications. Argo CD continuously checks the live cluster state and synchronizes it with the configurations stored in Git.",
    whyItsUsed: "Traditional CI/CD pipelines require giving CI build runners admin credentials to production Kubernetes clusters, creating major security vulnerabilities. Argo CD reverses this pattern: an in-cluster operator pulls changes from Git, detects configuration drift, provides automated rollbacks upon Git commit revert, and offers a visual dashboard showing the health and sync status of every Kubernetes resource.",
    architecture: "Argo CD runs inside the Kubernetes cluster. The Repo Server clones Git repositories and renders manifests (supporting plain YAML, Helm, Kustomize, and Jsonnet). The Application Controller compares the rendered desired state with live cluster state from the Kubernetes API. The Argo CD Server exposes the Web UI, CLI, and gRPC/REST APIs with RBAC integration.",
    keyFeatures: [
      "Automated Drift Detection & Self-Healing: Instantly alerts or automatically overwrites manual kubectl edits that violate Git declarations.",
      "Multi-Cluster Deployments: A single Argo CD instance can manage and synchronize applications across dozens of remote Kubernetes clusters.",
      "Intuitive Visual UI: Real-time graphical tree view of Pods, Services, Ingresses, Secrets, and status events.",
      "Enterprise RBAC & SSO: Integrates seamlessly with GitHub, GitLab, OIDC, and Okta for fine-grained permissions."
    ],
    quickstart: "# Install Argo CD into your Kubernetes cluster\nkubectl create namespace argocd\nkubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml\n\n# Access the Argo CD Web UI via port-forward\nkubectl port-forward svc/argocd-server -n argocd 8080:443",
    whenToUse: "The premier solution for any team practicing GitOps on Kubernetes. If you store your Helm charts or Kustomize manifests in Git, Argo CD is the natural choice for continuous delivery."
  },
  {
    id: "prometheus",
    name: "Prometheus",
    tagline: "The de-facto cloud-native metrics, time-series storage, and alerting engine.",
    category: "Observability & Monitoring",
    status: "CNCF Graduated",
    license: "Apache 2.0",
    stars: "55,000+",
    website: "https://prometheus.io",
    github: "https://github.com/prometheus/prometheus",
    icon: "/img/icons/prometheus.svg",
    tags: ["metrics", "monitoring", "promql", "cncf-graduated", "observability", "time-series"],
    whatItDoes: "Prometheus is an open-source systems monitoring and alerting toolkit originally built at SoundCloud and the second project to graduate from the CNCF after Kubernetes. It collects and stores metrics as time-series data, pairing timestamped numeric values with key-value dimensional labels.",
    whyItsUsed: "Modern cloud-native environments are dynamic, with containers spinning up and down continuously. Prometheus handles this with dynamic service discovery (e.g. querying Kubernetes API for live pods), a powerful multi-dimensional data model, and PromQL (Prometheus Query Language), allowing engineers to compute rates, percentiles (p95, p99), and SLI/SLO compliance with concise mathematical queries.",
    architecture: "Prometheus employs an autonomous pull model: it scrapes HTTP endpoints (like `/metrics`) exposed by targets at designated intervals. Scraped samples are written to a high-efficiency custom on-disk Time-Series Database (TSDB). The PromQL engine queries this data. Configured alerting rules evaluate continuously, sending triggered alerts to Alertmanager for deduplication, grouping, and dispatch (PagerDuty, Slack, email).",
    keyFeatures: [
      "Dimensional Data Model: Metrics identified by name and flexible key/value label pairs.",
      "PromQL: A powerful functional query language tailored for real-time aggregation and mathematical calculations over time windows.",
      "Dynamic Service Discovery: Automatically detects targets via Kubernetes, Consul, AWS EC2, Azure, and file-based mechanisms.",
      "Autonomous High Reliability: Each server is self-contained with zero external storage or clustered database dependencies."
    ],
    quickstart: "# Run Prometheus via Docker with default configuration\ndocker run -d --name prometheus -p 9090:9090 prom/prometheus\n\n# Query Prometheus metrics in browser\n# Open http://localhost:9090 and try: rate(http_requests_total[5m])",
    whenToUse: "The universal standard for infrastructure and application performance monitoring in cloud native and Kubernetes environments."
  },
  {
    id: "grafana",
    name: "Grafana",
    tagline: "The open observability platform for interactive dashboards, analytics, and metrics visualization.",
    category: "Observability & Monitoring",
    status: "Open Source Standard",
    license: "AGPL 3.0",
    stars: "63,000+",
    website: "https://grafana.com",
    github: "https://github.com/grafana/grafana",
    icon: "/img/icons/grafana.svg",
    tags: ["visualization", "dashboards", "observability", "metrics", "analytics", "monitoring"],
    whatItDoes: "Grafana is an open-source analytics and visualization web application. It enables teams to query, visualize, alert on, and understand metrics, logs, and distributed traces regardless of where they are stored. It acts as the unified 'single pane of glass' for engineering teams.",
    whyItsUsed: "Raw metric databases like Prometheus or log stores like Elasticsearch don't provide polished, interactive dashboards for human operators. Grafana bridges this gap with beautiful, responsive, and composable dashboards featuring graphs, heatmaps, gauges, geo-maps, and live status panels. It democratizes operational data across dev, ops, and executive teams.",
    architecture: "Grafana's backend is written in Go and serves a React frontend. Rather than storing data itself, Grafana connects to remote Data Sources (Prometheus, Loki, Tempo, InfluxDB, PostgreSQL, Datadog) via pluggable backend and frontend plugins. It translates user queries into data-source-specific queries, processes the returned data frames, and renders them in browser canvases.",
    keyFeatures: [
      "Pluggable Data Sources: Connect seamlessly to hundreds of data backends simultaneously in a single panel or dashboard.",
      "Templated Variables: Create dropdown variables (e.g. `$cluster`, `$namespace`, `$service`) that dynamically filter entire dashboards.",
      "Unified Alerting: Create alert rules combining multiple data sources and send alerts to Slack, Opsgenie, or Webhooks.",
      "Dashboard as Code: Provision and version-control dashboards in JSON or YAML via GitOps pipelines."
    ],
    quickstart: "# Launch Grafana via Docker\ndocker run -d --name=grafana -p 3000:3000 grafana/grafana\n\n# Open http://localhost:3000 (Default login: admin / admin)",
    whenToUse: "Indispensable for any organization needing to visualize operational telemetry, track business KPIs, or establish mission-control status boards for production environments."
  },
  {
    id: "helm",
    name: "Helm",
    tagline: "The package manager for Kubernetes — bundle, configure, and deploy complex apps with ease.",
    category: "Container & Orchestration",
    status: "CNCF Graduated",
    license: "Apache 2.0",
    stars: "26,000+",
    website: "https://helm.sh",
    github: "https://github.com/helm/helm",
    icon: "/img/icons/helm.svg",
    tags: ["packaging", "kubernetes", "yaml", "cncf-graduated", "charts", "deployment"],
    whatItDoes: "Helm is the package manager for Kubernetes. In the same way `apt` manages Debian packages or `npm` manages JavaScript libraries, Helm manages Kubernetes 'Charts'—pre-configured collections of Kubernetes resource manifests that define complete application architectures.",
    whyItsUsed: "Deploying a production application on Kubernetes often requires dozens of YAML files: Deployments, Services, ConfigMaps, Secrets, Ingresses, RBAC Roles, and ServiceAccounts. Copy-pasting and manually modifying raw YAML across dev, staging, and prod is tedious and error-prone. Helm parameterizes these templates using `values.yaml`, enabling one-line reproducible installs, upgrades, and rollbacks.",
    architecture: "Helm 3 is a client-only architecture with no server-side component (Tiller was removed in v3). The Helm CLI renders Go templates locally with user-supplied values, sends the final manifests directly to the Kubernetes API server using the user's standard `kubeconfig`, and records release state in Kubernetes Secrets within the target namespace.",
    keyFeatures: [
      "Chart Templating Engine: Leverage Go text templates to parameterize image tags, replica counts, ingress hosts, and environment variables.",
      "Versioned Releases: Track every rollout; roll back to previous releases with a single command (`helm rollback`).",
      "Chart Dependency Management: Specify child charts in `Chart.yaml` to automatically bundle databases, caches, and dependencies.",
      "Artifact Hub Ecosystem: Discover and install thousands of community and vendor-certified charts directly from public and private OCI registries."
    ],
    quickstart: "# Add Bitnami chart repository\nhelm repo add bitnami https://charts.bitnami.com/bitnami\nhelm repo update\n\n# Install Redis with custom password\nhelm install my-redis bitnami/redis --set auth.password=secret123",
    whenToUse: "Standard tool for packaging your team's internal microservices and installing third-party infrastructure components (Ingress NGINX, Cert-Manager, Prometheus stack) on Kubernetes."
  },
  {
    id: "cilium",
    name: "Cilium",
    tagline: "eBPF-powered cloud-native networking, security, and deep observability for modern clusters.",
    category: "Networking & Service Mesh",
    status: "CNCF Graduated",
    license: "Apache 2.0",
    stars: "19,000+",
    website: "https://cilium.io",
    github: "https://github.com/cilium/cilium",
    icon: "/img/icons/cilium.svg",
    tags: ["ebpf", "networking", "cni", "security", "cncf-graduated", "service-mesh", "hubble"],
    whatItDoes: "Cilium is an open-source software for transparently securing, routing, and observing network connectivity between container workloads. It is powered by extended Berkeley Packet Filter (eBPF)—a revolutionary Linux kernel technology that executes sandboxed programs inside the kernel without changing kernel source code or loading modules.",
    whyItsUsed: "Traditional Kubernetes networking uses Linux `iptables` or IPVS, which suffer severe performance degradation when clusters scale to thousands of services. Cilium eliminates `iptables` bottleneck completely by attaching eBPF programs directly to Linux network sockets. It also delivers sidecar-free service mesh capabilities, wireguard transparent encryption, and deep network flow observability via Hubble.",
    architecture: "Cilium runs as a DaemonSet (`cilium-agent`) on every Kubernetes node. As pods are scheduled, Cilium compiles specialized eBPF bytecode on the fly and attaches it to kernel hooks (XDP, tc, socket filters). Network packets are processed directly at the socket level in kernel space with zero user-space context-switching overhead.",
    keyFeatures: [
      "eBPF Kernel Performance: High-throughput, sub-millisecond network routing bypassing traditional iptables overhead.",
      "Identity-Based Security Policies: Define Layer 3 to Layer 7 security policies based on Kubernetes labels and DNS names rather than ephemeral IP addresses.",
      "Hubble Observability: Real-time visual network topology maps showing service dependencies, TCP latency, HTTP status codes, and packet drops.",
      "Sidecarless Service Mesh: Mutual TLS, Layer 7 traffic routing, and ingress controller capabilities without injecting resource-heavy Envoy sidecars into every pod."
    ],
    quickstart: "# Install Cilium CLI and install Cilium into your Kubernetes cluster\ncurl -L --remote-name https://github.com/cilium/cilium-cli/releases/latest/download/cilium-linux-amd64.tar.gz\ntar xzf cilium-linux-amd64.tar.gz\n./cilium install\n./cilium status",
    whenToUse: "The gold standard CNI for high-scale Kubernetes clusters, security-conscious organizations requiring zero-trust network policies, and teams wanting low-overhead service mesh."
  },
  {
    id: "vault",
    name: "HashiCorp Vault",
    tagline: "Secure, store, and tightly control access to tokens, passwords, certificates, and encryption keys.",
    category: "Security & Secrets",
    status: "Industry Standard",
    license: "BSL / Open Source Core",
    stars: "30,000+",
    website: "https://www.vaultproject.io",
    github: "https://github.com/hashicorp/vault",
    icon: "/img/icons/vault.svg",
    tags: ["secrets", "security", "encryption", "pki", "compliance", "zero-trust"],
    whatItDoes: "HashiCorp Vault is an enterprise-grade identity-based secrets and encryption management system. It provides a centralized, cryptographically fortified repository to store and govern access to API tokens, database credentials, SSH keys, TLS certificates, and sensitive environment variables.",
    whyItsUsed: "Hardcoding credentials in source code, Dockerfiles, or unencrypted Git repositories is the number one cause of enterprise cloud data breaches. Vault eliminates secret sprawl by providing dynamic on-demand secrets (e.g. creating unique PostgreSQL credentials with a 30-minute lease), automated key rotation, and centralized audit logging for strict regulatory compliance.",
    architecture: "Vault uses Shamir's Secret Sharing algorithm for its unseal process, ensuring no single operator can decrypt the master key. It features pluggable authentication backends (Kubernetes Service Accounts, AWS IAM, GitHub, LDAP), a granular ACL policy engine, and pluggable secret backends. All stored data is encrypted at rest using AES-256-GCM.",
    keyFeatures: [
      "Dynamic Secrets Generation: Generates credentials on-the-fly for AWS, databases, and message brokers with automatic revocation upon expiration.",
      "Encryption as a Service (Transit Engine): Encrypts application data in transit without the app needing to manage cryptographic key lifecycles.",
      "Automated PKI / TLS: Functions as a full internal Certificate Authority generating short-lived mTLS certs in milliseconds.",
      "Kubernetes Native Auth: Pods authenticate using their Kubernetes ServiceAccount tokens without needing any pre-seeded bootstrap secrets."
    ],
    quickstart: "# Start Vault in local development mode\nvault server -dev\n\n# Store and retrieve a secret\nexport VAULT_ADDR='http://127.0.0.1:8200'\nvault kv put secret/api-service api_key=\"prod_sk_99182\"\nvault kv get secret/api-service",
    whenToUse: "Mandatory for production systems handling sensitive credentials, multi-tenant cloud platforms, banking/healthcare applications, and teams enforcing Zero Trust architectures."
  },
  {
    id: "crossplane",
    name: "Crossplane",
    tagline: "The cloud native control plane framework to build custom Internal Developer Platforms (IDPs).",
    category: "Platform Engineering & IDP",
    status: "CNCF Graduated",
    license: "Apache 2.0",
    stars: "9,500+",
    website: "https://crossplane.io",
    github: "https://github.com/crossplane/crossplane",
    icon: "/img/icons/crossplane.svg",
    tags: ["platform-engineering", "control-plane", "kubernetes", "iac", "cncf-graduated", "self-service"],
    whatItDoes: "Crossplane transforms Kubernetes from a container orchestrator into a universal control plane capable of managing any external infrastructure or cloud service (AWS, GCP, Azure, GitHub, Snowflake) using native Kubernetes Custom Resource Definitions (CRDs).",
    whyItsUsed: "Terraform/OpenTofu is great for static provisioning, but operates as an external CLI pipeline that drifts over time. Crossplane brings Kubernetes' continuous reconciliation loop to cloud infrastructure. More importantly, it empowers platform teams to author custom 'Compositions'—abstracting complex multi-resource setups into simple, company-approved APIs that application developers can consume through standard `kubectl`.",
    architecture: "Crossplane installs inside a Kubernetes cluster and runs Provider pods (e.g. `provider-aws`). Each provider defines CRDs representing cloud primitives (Managed Resources). Platform teams bundle these primitives into Composite Resource Definitions (XRDs) and Compositions. When a developer submits a Claim (XRC), Crossplane generates the compliant cloud resources and continuously monitors for drift.",
    keyFeatures: [
      "Continuous Drift Reconciliation: Automatically restores cloud resources if someone manually tampers with them in the AWS/Azure console.",
      "Self-Service Developer APIs: Expose abstract types like `AppDatabase` to developers while platform engineers dictate security baselines, backups, and VPC peering.",
      "Unified Kubernetes Tooling: Manage databases, S3 buckets, and IAM using GitOps, Argo CD, Helm, and Kustomize just like pods.",
      "Multi-Cloud Abstraction: Switch underlying cloud providers under the hood without changing application developer deployment manifests."
    ],
    quickstart: "# Install Crossplane via Helm\nhelm repo add crossplane-stable https://charts.crossplane.io/stable\nhelm install crossplane --namespace crossplane-system --create-namespace crossplane-stable/crossplane\n\n# Inspect Crossplane pods\nkubectl get pods -n crossplane-system",
    whenToUse: "The cornerstone of modern Platform Engineering teams aiming to deliver self-service cloud infrastructure to developers without giving everyone raw cloud console admin access."
  },
  {
    id: "backstage",
    name: "Backstage",
    tagline: "Spotify's open-source framework for building unified Internal Developer Portals (IDPs).",
    category: "Platform Engineering & IDP",
    status: "CNCF Incubating",
    license: "Apache 2.0",
    stars: "28,000+",
    website: "https://backstage.io",
    github: "https://github.com/backstage/backstage",
    icon: "/img/icons/backstage.svg",
    tags: ["platform-engineering", "idp", "developer-portal", "cncf-incubating", "spotify", "catalog"],
    whatItDoes: "Backstage is an open platform created by Spotify and donated to the CNCF for building developer portals. Centered around a centralized Software Catalog, Backstage restores order to microservice architectures by centralizing service ownership, documentation, CI/CD visibility, and standardized software scaffolding.",
    whyItsUsed: "As engineering organizations grow, cognitive load explodes: developers don't know who owns which microservice, where APIs are documented, which CI pipeline failed, or how to spin up a compliant new service. Backstage provides a unified, customizable web interface that accelerates developer onboarding and enforces enterprise standards.",
    architecture: "Backstage is built with a Node.js/TypeScript backend and a React frontend. Its architecture is heavily plugin-based. Core plugins include the Software Catalog (ingests `catalog-info.yaml` files from Git), Software Templates (scaffolds new repositories using cookiecutter/Yeoman templates), and TechDocs (renders Markdown documentation from Git with MkDocs).",
    keyFeatures: [
      "Centralized Software Catalog: Comprehensive registry tracking services, APIs, libraries, websites, and system ownership across all teams.",
      "Software Templates (Golden Paths): Enable developers to create new microservices with pre-configured CI/CD, linting, and Kubernetes manifests in 5 minutes.",
      "TechDocs (Docs-Like-Code): Write documentation in Markdown inside Git repositories and have Backstage automatically build and index searchable documentation.",
      "Massive Plugin Ecosystem: Integrate with GitHub, Jira, Datadog, Sentry, Kubernetes, PagerDuty, and SonarQube out of the box."
    ],
    quickstart: "# Scaffold a new Backstage developer portal instance\nnpx @backstage/create-app@latest\n\n# Navigate to project and launch local dev server\ncd my-backstage-app\nyarn start",
    whenToUse: "Essential for growing tech companies with dozens or hundreds of engineers experiencing microservice sprawl, documentation fragmentation, and slow team onboarding."
  },
  {
    id: "opentelemetry",
    name: "OpenTelemetry",
    tagline: "High-quality, ubiquitous, and vendor-neutral telemetry for distributed traces, metrics, and logs.",
    category: "Observability & Monitoring",
    status: "CNCF Graduated",
    license: "Apache 2.0",
    stars: "5,000+",
    website: "https://opentelemetry.io",
    github: "https://github.com/open-telemetry",
    icon: "/img/icons/opentelemetry.svg",
    tags: ["telemetry", "tracing", "metrics", "logs", "cncf-graduated", "vendor-neutral", "collector"],
    whatItDoes: "OpenTelemetry (often called OTel) is an observability framework that provides a single, standardized set of APIs, SDKs, and tooling to generate, collect, and export telemetry data (traces, metrics, and logs) from cloud-native software.",
    whyItsUsed: "Historically, instrumenting an application locked you into a proprietary vendor's SDK (Datadog, New Relic, Dynatrace). Switching vendors required rewriting application code across hundreds of repositories. OpenTelemetry decouples application instrumentation from the backend storage. You instrument your code once using open standards, and route data anywhere.",
    architecture: "OTel consists of Language SDKs (Java, Python, Go, Node.js, .NET, Rust) with auto-instrumentation agents that capture HTTP/gRPC calls and database queries. Telemetry is emitted via the standardized OTLP protocol to an OpenTelemetry Collector. The Collector has three pipeline stages: Receivers (ingest data), Processors (batch, filter, redact PII), and Exporters (send to Prometheus, Jaeger, Datadog, or Grafana).",
    keyFeatures: [
      "Vendor-Neutral Standard: Avoid vendor lock-in forever; change telemetry storage destinations by editing a single YAML configuration.",
      "Automated Instrumentation: Drop-in zero-code agents automatically trace HTTP frameworks, database clients, and messaging queues.",
      "High-Performance Collector: Standalone proxy to aggregate, batch, sample, and scrub sensitive data before sending it out of your private VPC.",
      "Unified Signals: Correlate distributed traces directly to infrastructure metrics and application log lines using shared TraceId and SpanId."
    ],
    quickstart: "# Run OpenTelemetry Collector locally via Docker\ndocker run -p 4317:4317 -p 4318:4318 -p 8889:8889 otel/opentelemetry-collector:latest",
    whenToUse: "The standard choice for any modern microservice architecture looking to implement distributed tracing and telemetry without risking vendor lock-in."
  },
  {
    id: "trivy",
    name: "Trivy",
    tagline: "Comprehensive, lightning-fast vulnerability, misconfiguration, secret, and SBOM scanner.",
    category: "Security & Secrets",
    status: "Open Source (Aqua Security)",
    license: "Apache 2.0",
    stars: "23,000+",
    website: "https://trivy.dev",
    github: "https://github.com/aquasecurity/trivy",
    icon: "/img/icons/trivy.svg",
    tags: ["security", "vulnerability-scanner", "cve", "iac-scan", "sbom", "container-security"],
    whatItDoes: "Trivy is a versatile, developer-friendly open-source security scanner. It scans container images, Git code repositories, virtual machine filesystems, Kubernetes clusters, and IaC files (Terraform, Dockerfiles, Kubernetes manifests) for known Common Vulnerabilities and Exposures (CVEs), hardcoded secrets, and misconfigurations.",
    whyItsUsed: "Security checks are often painful and slow down software delivery. Trivy is built for extreme speed and simplicity: it requires zero installation of heavy backend databases. Engineers can run it directly on developer laptops or inside CI/CD pipelines to catch vulnerabilities and reject builds before insecure code ever reaches production.",
    architecture: "Trivy is written in Go as a standalone statically linked binary. It maintains an embedded vulnerability database compiled from national CVE databases, Red Hat, Debian, Ubuntu, Alpine, GitHub Advisories, and language package managers. It automatically downloads database deltas in seconds on first run.",
    keyFeatures: [
      "All-In-One Scanning: Detects OS package CVEs, language dependencies (npm, pip, go, maven), hardcoded API tokens, and IaC security misconfigurations.",
      "Software Bill of Materials (SBOM): Generates and scans industry-standard SBOM formats (SPDX, CycloneDX) for supply chain security.",
      "Zero Dependency & Fast: Scans a standard Docker image in 2 to 5 seconds with accurate results and low false positives.",
      "CI/CD and K8s Operator: Native integration with GitHub Actions, GitLab CI, and runs as an in-cluster Kubernetes operator."
    ],
    quickstart: "# Scan a Docker image for vulnerabilities\ntrivy image node:20-alpine\n\n# Scan a local git directory for hardcoded secrets and misconfigs\ntrivy fs --security-checks config,secret .",
    whenToUse: "A must-have security gate for every CI/CD pipeline, container registry build process, and platform engineering supply chain."
  },
  {
    id: "istio",
    name: "Istio",
    tagline: "Full-featured service mesh providing zero-trust security, traffic routing, and deep observability.",
    category: "Networking & Service Mesh",
    status: "CNCF Graduated",
    license: "Apache 2.0",
    stars: "35,000+",
    website: "https://istio.io",
    github: "https://github.com/istio/istio",
    icon: "/img/icons/istio.svg",
    tags: ["service-mesh", "mtls", "traffic-management", "cncf-graduated", "envoy", "zero-trust"],
    whatItDoes: "Istio is a leading open-source service mesh that transparently layers on top of existing distributed applications. It manages service-to-service communication across microservice architectures, providing encrypted traffic, fine-grained routing, and telemetry without changing a single line of application source code.",
    whyItsUsed: "When companies split monoliths into hundreds of microservices, managing network traffic, timeouts, retries, mutual TLS certificate rotation, and canary rollouts at the application level becomes an unmaintainable nightmare. Istio abstracts these network concerns into the platform layer.",
    architecture: "Istio splits into a Control Plane (`istiod`) and a Data Plane. In classic mode, it injects an Envoy proxy sidecar alongside each application pod (and in Ambient Mesh mode, runs as node-level Layer 4 proxies). `istiod` compiles high-level routing rules and security policies into dynamic Envoy configurations via xDS APIs.",
    keyFeatures: [
      "Automatic Mutual TLS (mTLS): Enforces zero-trust cryptographic encryption and identity authentication between all microservices.",
      "Advanced Traffic Routing: Execute canary deployments, percentage-based splits, A/B testing, circuit breakers, and fault injection.",
      "Declarative Authorization Policies: Control exactly which services are permitted to communicate based on cryptographic identities (SPIFFE).",
      "Comprehensive L7 Metrics: Generates golden metrics (latency, traffic, errors, saturation) for all HTTP, gRPC, and TCP traffic."
    ],
    quickstart: "# Download and install Istio using istioctl\ncurl -L https://istio.io/downloadIstio | sh -\ncd istio-*\n./bin/istioctl install --set profile=demo -y\n\n# Enable automatic sidecar injection on default namespace\nkubectl label namespace default istio-injection=enabled",
    whenToUse: "Ideal for enterprise microservice architectures requiring strict Zero Trust compliance, automated mTLS, and advanced canary or blue-green traffic management."
  },
  {
    id: "falco",
    name: "Falco",
    tagline: "The cloud-native runtime security monitor and zero-day threat detection engine.",
    category: "Security & Secrets",
    status: "CNCF Graduated",
    license: "Apache 2.0",
    stars: "7,500+",
    website: "https://falco.org",
    github: "https://github.com/falcosecurity/falco",
    icon: "/img/icons/falco.svg",
    tags: ["runtime-security", "ebpf", "threat-detection", "cncf-graduated", "zero-day", "kernel"],
    whatItDoes: "Falco is the open-source behavioral runtime security monitor designed for Linux containers and Kubernetes. Created by Sysdig and graduated by the CNCF, Falco functions like a security surveillance camera inside Linux systems, alerting in real-time when malicious or anomalous behavior occurs.",
    whyItsUsed: "Static vulnerability scanners like Trivy check code before deployment, but cannot protect against zero-day exploits, compromised root credentials, or malicious insider actions occurring at runtime. Falco catches active attacks in progress: unauthorized shell spawns inside production pods, unexpected namespace modifications, or modifications to sensitive files like `/etc/shadow`.",
    architecture: "Falco hooks directly into the Linux kernel via an eBPF probe or kernel driver. Every system call (file read, process exec, network connection) is captured at the kernel level and evaluated against a rich rules engine written in declarative YAML. Alerts are dispatched to standard out, gRPC endpoints, webhooks, or automated response frameworks (Falco Sidekick).",
    keyFeatures: [
      "Kernel-Level System Call Visibility: Unmatched visibility into process spawns, file system access, and network connections.",
      "Declarative YAML Rule Syntax: Write custom behavioral policies or use hundreds of out-of-the-box rules mapped to the MITRE ATT&CK framework.",
      "Kubernetes Context Enrichment: Alerts automatically include Kubernetes pod names, namespaces, deployment names, and image tags.",
      "Zero-Day Threat Detection: Detects anomalies based on behavioral deviations rather than static signature matching."
    ],
    quickstart: "# Install Falco into Kubernetes using Helm\nhelm repo add falcosecurity https://falcosecurity.github.io/charts\nhelm repo update\nhelm install falco falcosecurity/falco --namespace falco --create-namespace",
    whenToUse: "Crucial for organizations needing real-time intrusion detection, compliance monitoring (PCI-DSS, SOC2, HIPAA), and runtime container defense."
  },
  {
    id: "flux",
    name: "Flux CD",
    tagline: "Composable, secure, and extensible continuous delivery solution built on the GitOps Toolkit.",
    category: "CI/CD & GitOps",
    status: "CNCF Graduated",
    license: "Apache 2.0",
    stars: "14,000+",
    website: "https://fluxcd.io",
    github: "https://github.com/fluxcd/flux2",
    icon: "/img/icons/flux.svg",
    tags: ["gitops", "continuous-delivery", "cncf-graduated", "kubernetes", "automation", "oci"],
    whatItDoes: "Flux CD is an open-source tool suite that brings GitOps to Kubernetes. It maintains Kubernetes cluster configuration in synchronization with sources like Git repositories, OCI registries, and S3-compatible storage buckets.",
    whyItsUsed: "Flux follows the Unix philosophy of doing one thing well through modular components called the GitOps Toolkit. It provides multi-tenancy out of the box, natively handles Helm releases with automatic rollbacks, and can automatically monitor container registries for new image tags and commit them back to your Git repository.",
    architecture: "Flux is composed of dedicated Kubernetes Custom Controllers: Source Controller (fetches artifacts from Git/Helm/OCI), Kustomize Controller (reconciles raw manifests and overlays), Helm Controller (automates Helm chart lifecycles), Notification Controller (handles webhook events and alerts), and Image Automation Controller.",
    keyFeatures: [
      "Modular GitOps Toolkit: Use only the controllers you need; build custom GitOps workflows using standard Kubernetes CRDs.",
      "Automated Image Updates: Automatically detects new container image tags in registries and creates Git pull requests or direct commits.",
      "Native OCI Artifact Support: Store and distribute Kubernetes manifests and Helm charts as OCI artifacts in container registries alongside Docker images.",
      "Multi-Tenancy & Security: Strictly enforces Kubernetes RBAC permissions per tenant and supports GPG/Cosign signature verification."
    ],
    quickstart: "# Install Flux CLI and verify cluster prerequisites\ncurl -s https://fluxcd.io/install.sh | sudo bash\nflux check --pre\n\n# Bootstrap Flux with your GitHub repository\nflux bootstrap github --owner=$GITHUB_USER --repository=fleet-infra --path=clusters/my-cluster",
    whenToUse: "A fantastic alternative or companion to Argo CD, especially for platform teams prioritizing native Kubernetes controllers, automated image-to-Git commits, and OCI packaging."
  },
  {
    id: "jaeger",
    name: "Jaeger",
    tagline: "Open-source, end-to-end distributed tracing for cloud-native microservices.",
    category: "Observability & Monitoring",
    status: "CNCF Graduated",
    license: "Apache 2.0",
    stars: "19,000+",
    website: "https://www.jaegertracing.io",
    github: "https://github.com/jaegertracing/jaeger",
    icon: "/img/icons/jaeger.svg",
    tags: ["distributed-tracing", "observability", "latency", "cncf-graduated", "microservices", "debugging"],
    whatItDoes: "Jaeger is a distributed tracing platform originally created at Uber and graduated by the CNCF. It monitors and troubleshoots complex microservice interactions by tracking transactions as they traverse asynchronous queues, RPC calls, and network hops.",
    whyItsUsed: "In a microservices architecture, a single user click may trigger requests across twenty different backend services. When a request times out or returns a 500 error, logs alone cannot reveal which downstream service failed or caused the latency spike. Jaeger visualizes each request as a flame-graph waterfall timeline.",
    architecture: "Applications instrumented with OpenTelemetry send span data to Jaeger Collectors. The Collectors validate, index, and write traces to persistent storage (Elasticsearch, OpenSearch, or Cassandra). The Jaeger Query daemon retrieves traces and renders them in the interactive Jaeger Web UI.",
    keyFeatures: [
      "Distributed Context Propagation: Correlates distributed operations across HTTP, gRPC, and message brokers like Kafka.",
      "Interactive Waterfall Visualizations: Inspect exact latency contribution of every function call and database query in a request trace.",
      "Root Cause Analysis: Filter traces by duration, tags, and error flags to rapidly identify failed dependencies.",
      "Native OpenTelemetry Integration: Fully compliant with OpenTelemetry standards and the W3C TraceContext specification."
    ],
    quickstart: "# Run Jaeger all-in-one image locally for quick testing\ndocker run -d --name jaeger -p 16686:16686 -p 4317:4317 -p 4318:4318 jaegertracing/all-in-one:latest\n\n# Open Jaeger UI in your browser\n# http://localhost:16686",
    whenToUse: "Essential for debugging latency bottlenecks, tracking distributed errors, and mapping service dependencies across modern microservice applications."
  },
  {
    id: "cert-manager",
    name: "Cert-Manager",
    tagline: "Automated X.509 TLS certificate issuance, validation, and renewal for Kubernetes.",
    category: "Security & Secrets",
    status: "CNCF Graduated",
    license: "Apache 2.0",
    stars: "12,000+",
    website: "https://cert-manager.io",
    github: "https://github.com/cert-manager/cert-manager",
    icon: "/img/icons/cert-manager.svg",
    tags: ["certificates", "tls", "security", "cncf-graduated", "kubernetes", "automation", "acme"],
    whatItDoes: "Cert-Manager is the cloud-native certificate controller for Kubernetes. It automates the management, issuance, and renewal of SSL/TLS certificates from a variety of sources, including Let's Encrypt (via ACME HTTP-01/DNS-01), HashiCorp Vault, Venafi, or in-cluster Certificate Authorities.",
    whyItsUsed: "Expired TLS certificates cause high-visibility public outages and broken service-to-service communication. Manually buying, generating, and copying certificate files into Kubernetes Secrets is error-prone. Cert-Manager ensures certificates are valid and automatically renewed weeks before expiration.",
    architecture: "Cert-Manager runs as a set of Kubernetes controllers and webhooks. It introduces custom resources such as `Certificate`, `Issuer`, and `ClusterIssuer`. When a Certificate resource is created (or an Ingress is annotated), Cert-Manager solves ACME challenges, requests certificate issuance, and stores the resulting keypair in a native Kubernetes Secret.",
    keyFeatures: [
      "Automated ACME Challenge Resolution: Handles Let's Encrypt HTTP-01 and DNS-01 challenges across major DNS providers (Cloudflare, Route53, Google Cloud DNS).",
      "Ingress Shim Integration: Simply add `cert-manager.io/cluster-issuer: letsencrypt-prod` annotation to your Ingress for instant automatic HTTPS.",
      "Multiple Issuers: Supports public ACME authorities, private PKI, HashiCorp Vault, and internal self-signed development certificates.",
      "Proactive Renewal: Automatically initiates renewal well in advance of certificate expiry date to prevent downtime."
    ],
    quickstart: "# Install cert-manager with custom CRDs\nkubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.14.0/cert-manager.yaml\n\n# Verify pods are running in cert-manager namespace\nkubectl get pods -n cert-manager",
    whenToUse: "A universal prerequisite for any production Kubernetes cluster running web services, APIs, or internal microservices requiring automated HTTPS."
  },
  {
    id: "keda",
    name: "KEDA",
    tagline: "Kubernetes Event-driven Autoscaling — scale workloads based on any event stream.",
    category: "Container & Orchestration",
    status: "CNCF Graduated",
    license: "Apache 2.0",
    stars: "8,500+",
    website: "https://keda.sh",
    github: "https://github.com/kedacore/keda",
    icon: "/img/icons/keda.svg",
    tags: ["autoscaling", "event-driven", "kubernetes", "cncf-graduated", "serverless", "scaling"],
    whatItDoes: "KEDA (Kubernetes Event-driven Autoscaling) is an application autoscaler that enables containers to scale dynamically from 0 to thousands of replicas based on the volume of events waiting in queues, databases, or stream brokers.",
    whyItsUsed: "Standard Kubernetes Horizontal Pod Autoscaler (HPA) can only scale based on CPU and memory usage. For event-driven workers processing Kafka messages or AWS SQS queues, CPU usage stays low even if millions of messages are queued up, causing processing backlogs. Furthermore, native HPA cannot scale pods down to 0. KEDA solves both limitations.",
    architecture: "KEDA acts as a metrics adapter for Kubernetes HPA. It runs an operator and a Metrics Server. The operator polls external event sources using pluggable scalers (over 60 built-in scalers for Kafka, RabbitMQ, Redis, Prometheus, AWS, Azure, GCP). When events arrive, KEDA scales the target deployment from 0 to 1, then hands over metrics to native HPA for further scaling.",
    keyFeatures: [
      "Scale to Zero: Completely deactivate pods when queues are empty to minimize cloud compute costs.",
      "60+ Out-of-the-Box Scalers: Native support for Apache Kafka, RabbitMQ, Redis, AWS SQS, Azure Service Bus, GCP Pub/Sub, and Prometheus queries.",
      "Works with Native Kubernetes: Complements rather than replaces standard Kubernetes Horizontal Pod Autoscalers.",
      "Custom CRD Simplicity: Configure autoscaling rules in a simple `ScaledObject` YAML file."
    ],
    quickstart: "# Install KEDA using Helm\nhelm repo add kedacore https://kedacore.github.io/charts\nhelm repo update\nhelm install keda kedacore/keda --namespace keda --create-namespace",
    whenToUse: "Ideal for background worker pools, asynchronous event processing, Kafka stream consumers, and cost-conscious architectures running on Kubernetes."
  },
  {
    id: "k9s",
    name: "K9s",
    tagline: "Kubernetes terminal UI to manage your clusters with unmatched speed and style.",
    category: "Platform Engineering & IDP",
    status: "Open Source Community",
    license: "Apache 2.0",
    stars: "28,000+",
    website: "https://k9scli.io",
    github: "https://github.com/derailed/k9s",
    icon: "/img/icons/k9s.svg",
    tags: ["tui", "cli", "kubernetes", "productivity", "debugging", "terminal"],
    whatItDoes: "K9s is a terminal-based UI (TUI) for interacting with Kubernetes clusters. It provides an intuitive, keyboard-driven dashboard that accelerates day-to-day cluster operations, resource inspection, troubleshooting, and management.",
    whyItsUsed: "Typing verbose commands like `kubectl get pods -n production -l app=payment-service --sort-by=.status.startTime` dozens of times a day is slow and tedious. K9s brings rapid keyboard shortcuts, live log streaming, interactive container exec, port-forwarding, and resource editing into a single lightweight terminal screen.",
    architecture: "K9s is a single compiled Go binary. It uses the `tcell` and `tview` terminal UI libraries. It communicates directly with the current Kubernetes context from your local `~/.kube/config`, maintaining lightweight watches on API resources without deploying any server components into the cluster.",
    keyFeatures: [
      "Instant Resource Navigation: Jump between pods, services, deployments, CRDs, and logs with vim-like keyboard shortcuts.",
      "Real-Time Log Streaming & Filtering: View aggregated pod logs, wrap lines, and filter live errors in real time.",
      "Interactive Port-Forwarding & Shell: Open an interactive shell inside any container or port-forward services with two keystrokes.",
      "Resource Utilization Gauges: Live indicators of CPU and memory consumption per pod and node based on metrics-server data."
    ],
    quickstart: "# Install K9s via Homebrew or curl and run\ncurl -sS https://webi.sh/k9s | sh\n\n# Launch K9s in terminal\nk9s",
    whenToUse: "The daily-driver productivity tool of choice for every DevOps, SRE, and Kubernetes cluster administrator."
  },
  {
    id: "loki",
    name: "Loki",
    tagline: "Like Prometheus, but for logs: horizontally scalable, multi-tenant log aggregation.",
    category: "Observability & Monitoring",
    status: "Open Source (Grafana Labs)",
    license: "AGPL 3.0",
    stars: "24,000+",
    website: "https://grafana.com/oss/loki",
    github: "https://github.com/grafana/loki",
    icon: "/img/icons/loki.svg",
    tags: ["logging", "observability", "logql", "grafana", "cloud-native", "storage"],
    whatItDoes: "Grafana Loki is a horizontally scalable, highly available, multi-tenant log aggregation system inspired by Prometheus. It is designed to be cost-effective and easy to operate.",
    whyItsUsed: "Traditional log management tools (like Elasticsearch) index the full text of every log message, requiring massive RAM and disk overhead that inflates cloud bills. Loki indexes only the metadata labels (like Kubernetes namespace, pod, or environment) while storing raw compressed log streams directly in cheap object storage (S3, GCS, Azure Blob).",
    architecture: "Loki uses agents like Promtail, Fluentbit, or the OpenTelemetry Collector to tail log files and attach label metadata. Logs are sent to the Loki Distributor, buffered in the Ingestor, and flushed as compressed chunks to cloud object storage. Queries are parsed with LogQL, enabling regex matching and metric generation directly from logs.",
    keyFeatures: [
      "Label-Only Indexing: Extremely low storage and RAM consumption compared to traditional full-text search engines.",
      "LogQL Query Language: Powerful syntax that allows filtering logs and generating real-time metrics (e.g. error rate per second) from log streams.",
      "Native Grafana Integration: Seamlessly correlate metrics in Grafana with corresponding logs by clicking on a spike in a Prometheus graph.",
      "Multi-Tenancy & Chunk Compression: Built-in tenant separation and high gzip compression ratios for cost-efficient log retention."
    ],
    quickstart: "# Run Loki via Docker\ndocker run -d --name=loki -p 3100:3100 grafana/loki:latest",
    whenToUse: "The ideal logging backend for teams already running Prometheus and Grafana who want high-volume log storage without massive infrastructure costs."
  },
  {
    id: "envoy",
    name: "Envoy",
    tagline: "High-performance, small-footprint cloud-native edge and service proxy.",
    category: "Networking & Service Mesh",
    status: "CNCF Graduated",
    license: "Apache 2.0",
    stars: "25,000+",
    website: "https://www.envoyproxy.io",
    github: "https://github.com/envoyproxy/envoy",
    icon: "/img/icons/envoy.svg",
    tags: ["proxy", "networking", "grpc", "http2", "cncf-graduated", "gateway", "edge"],
    whatItDoes: "Envoy is an open-source edge and service proxy designed for cloud-native applications. Originally built at Lyft, Envoy provides universal data-plane capabilities for microservices, modern service meshes, and API gateways.",
    whyItsUsed: "Traditional proxies (like older versions of NGINX or HAProxy) required static configuration files and restarts when service IP addresses changed. Envoy was engineered from day one for dynamic cloud environments with dynamic discovery services (xDS), deep L7 observability, first-class gRPC and HTTP/2 support, and circuit breaking.",
    architecture: "Written in C++ for maximum throughput and minimal memory footprint, Envoy uses an asynchronous, event-driven threading model. Worker threads listen for connections and route them through customizable filter chains. Envoy dynamically retrieves cluster, listener, and route configurations over gRPC via dynamic xDS APIs.",
    keyFeatures: [
      "Dynamic Discovery APIs (xDS): Dynamically reconfigure listeners, routes, and upstream clusters without restarting the proxy.",
      "First-Class HTTP/2 & gRPC: Transparently translates between HTTP/1.1, HTTP/2, and gRPC with bidirectional streaming support.",
      "Advanced Resiliency: Configurable connection pooling, outlier detection, circuit breaking, rate limiting, and retries.",
      "Rich Telemetry: Emits detailed stats for every downstream request and upstream connection to Prometheus and StatsD."
    ],
    quickstart: "# Launch official Envoy container\ndocker run -d --name envoy -p 10000:10000 envoyproxy/envoy:v1.30-latest\n\n# Test default admin endpoint\ncurl http://localhost:10000"
  },
  {
    id: "pulumi",
    name: "Pulumi",
    tagline: "Infrastructure as Code using real programming languages: TypeScript, Python, Go, and C#.",
    category: "Infrastructure as Code",
    status: "Open Source",
    license: "Apache 2.0",
    stars: "20,000+",
    website: "https://www.pulumi.com",
    github: "https://github.com/pulumi/pulumi",
    icon: "/img/icons/pulumi.svg",
    tags: ["iac", "typescript", "python", "multi-cloud", "programming-languages", "cloud-engineering"],
    whatItDoes: "Pulumi is an open-source Infrastructure as Code SDK that allows engineers to provision, configure, and manage cloud infrastructure using real general-purpose programming languages like TypeScript, Python, Go, C#, and Java.",
    whyItsUsed: "Domain-specific languages like HCL (Terraform) can feel limiting when teams need complex loops, condition branching, custom abstractions, unit testing, and IDE autocomplete. Pulumi empowers developers to write infrastructure using the languages, package managers (npm, pip), and test suites they already know and love.",
    architecture: "Pulumi programs run within standard language runtimes (Node.js, Python). When executed, the Pulumi language SDK communicates via gRPC with the Pulumi Engine. The engine constructs an immutable resource graph, calculates diffs against state, and talks to Cloud Resource Providers to provision resources.",
    keyFeatures: [
      "Real Programming Languages: Use loops, functions, classes, and object inheritance to structure complex infrastructure architectures.",
      "Full IDE Power: Benefit from autocompletion, type-checking, inline documentation, and refactoring tools.",
      "Unit & Integration Testing: Test infrastructure code using standard testing frameworks like Jest, PyTest, or Go test.",
      "Cross-Language Components: Create reusable cloud architecture packages and publish them for team consumption via npm or PyPI."
    ],
    quickstart: "# Install Pulumi CLI and initialize a new project\ncurl -fsSL https://get.pulumi.com | sh\npulumi new aws-typescript\n\n# Preview and deploy infrastructure\npulumi up"
  },
  {
    id: "podman",
    name: "Podman",
    tagline: "Daemonless, rootless container engine for developing and running OCI containers securely.",
    category: "Containerization",
    status: "Open Source (Red Hat)",
    license: "Apache 2.0",
    stars: "23,000+",
    website: "https://podman.io",
    github: "https://github.com/containers/podman",
    icon: "/img/icons/podman.svg",
    tags: ["rootless", "daemonless", "containers", "security", "linux", "oci"],
    whatItDoes: "Podman (Pod Manager) is a daemonless, open-source Linux tool designed for developing, managing, and running OCI containers and container pods. It serves as an alias-compatible drop-in replacement for Docker.",
    whyItsUsed: "Docker requires a background daemon running as root, introducing security vulnerabilities and a single point of failure. Podman runs containers rootless by default: if a container process breaks out, it only possesses the unprivileged rights of the standard user. Furthermore, Podman natively generates and executes Kubernetes pod YAMLs.",
    architecture: "Podman uses a traditional fork-exec model: when you run a container, Podman spawns `crun` or `runc` as a child process directly using Linux user namespaces. There is no resident background daemon process. Podman also provides an optional Docker-compatible REST socket for tools like Docker Compose and VS Code Dev Containers.",
    keyFeatures: [
      "Rootless by Default: Run and manage containers without needing sudo or root privileges on the host system.",
      "Daemonless Operation: Containers run as independent child processes; restarting or killing Podman does not drop running containers.",
      "Kubernetes Native: Generate Kubernetes pod YAML from running containers (`podman generate kube`) and run pod YAML directly (`podman play kube`).",
      "Docker CLI Alias: Compatible command syntax (`alias docker=podman`) allows transparent drop-in replacement."
    ],
    quickstart: "# Run an nginx container rootless\npodman run -d --name web -p 8080:80 nginx:alpine\n\n# Generate Kubernetes YAML from running container\npodman generate kube web > web-pod.yaml",
    whenToUse: "The preferred choice for security-stringent environments, multi-user HPC systems, and Linux developers seeking daemonless container execution."
  },
  {
    id: "jenkins",
    name: "Jenkins",
    tagline: "The battle-tested, extensible open source automation server for CI/CD pipelines.",
    category: "CI/CD & GitOps",
    status: "CD Foundation",
    license: "MIT",
    stars: "23,000+",
    website: "https://www.jenkins.io",
    github: "https://github.com/jenkinsci/jenkins",
    icon: "/img/icons/jenkins.svg",
    tags: ["ci-cd", "automation", "pipeline", "battle-tested", "plugins", "groovy"],
    whatItDoes: "Jenkins is an open-source automation server that provides hundreds of plugins to support building, deploying, and automating any software project.",
    whyItsUsed: "Jenkins is the grandfather of continuous integration. While modern GitOps tools excel at Kubernetes rollouts, Jenkins remains unmatched in its flexibility for orchestrating complex, multi-system legacy pipelines, hardware testing, and hybrid on-premise workflows. Its vast plugin library connects to virtually every tool in computing history.",
    architecture: "Jenkins uses a controller-agent distributed architecture. The Jenkins Controller hosts the web interface, manages configuration, and schedules build tasks. Dynamic Agent nodes (spinning up on demand as Kubernetes pods, Docker containers, or EC2 instances) execute the actual build steps.",
    keyFeatures: [
      "Pipeline as Code: Define complex multi-stage pipelines in version-controlled Groovy `Jenkinsfile` scripts.",
      "1,800+ Plugins: Integrate with any source control, testing framework, artifact repository, or notification channel.",
      "Distributed Build Agents: Dynamically scale ephemeral build worker pods in Kubernetes clusters.",
      "Self-Hosted Sovereignty: Full control over your build infrastructure, source code security, and compliance boundaries."
    ],
    quickstart: "# Run Jenkins locally via Docker\ndocker run -p 8080:8080 -p 50000:50000 -v jenkins_home:/var/jenkins_home jenkins/jenkins:lts-jdk17"
  }
];

const SEED_REVIEWS = [
  {
    productId: "kubernetes",
    author: "sre_alex",
    role: "Lead Site Reliability Engineer",
    experience: "Daily Production Driver",
    rating: 5,
    whatLiked: "Self-healing and declarative reconciliation are magical. Once configured properly, it runs for months without human intervention.",
    gotchas: "Steep learning curve. Networking (CNI, Ingress) and storage classes require deep initial investment.",
    comment: "Kubernetes transformed how our engineering team operates. We run 40+ microservices with automated rollouts and zero downtime deployments.",
    upvotes: 42,
    createdAt: "2026-08-12T10:15:00.000Z"
  },
  {
    productId: "kubernetes",
    author: "platform_priya",
    role: "Staff Platform Engineer",
    experience: "Used in Production (3+ yrs)",
    rating: 5,
    whatLiked: "Extensibility through CRDs and custom operators makes it the ultimate platform for building developer platforms.",
    gotchas: "Don't write raw YAML by hand; use Helm, Kustomize, or Argo CD from day one.",
    comment: "Paired with Argo CD and Cilium, Kubernetes is unbeatable for enterprise infrastructure.",
    upvotes: 28,
    createdAt: "2026-08-20T14:32:00.000Z"
  },
  {
    productId: "docker",
    author: "dev_marcus",
    role: "Full Stack Tech Lead",
    experience: "Daily Production Driver",
    rating: 5,
    whatLiked: "Multi-stage builds make container images tiny, secure, and fast to download across CI runners.",
    gotchas: "Clean up unused images regularly (`docker system prune`) or your disk fills up fast.",
    comment: "It completely solved our team's onboarding troubles. New developers can spin up the full stack in 2 minutes with Docker Compose.",
    upvotes: 35,
    createdAt: "2026-08-05T09:40:00.000Z"
  },
  {
    productId: "opentofu",
    author: "cloud_sam",
    role: "Principal Cloud Architect",
    experience: "Daily Production Driver",
    rating: 5,
    whatLiked: "Truly open source governance under the Linux Foundation. Drop-in replacement for Terraform with zero migration friction.",
    gotchas: "Always protect remote state files with encryption and state locking (e.g. S3 + DynamoDB).",
    comment: "We migrated our entire multi-account AWS infrastructure from Terraform to OpenTofu in an afternoon. Clean, fast, and community-first.",
    upvotes: 31,
    createdAt: "2026-08-18T16:20:00.000Z"
  },
  {
    productId: "argocd",
    author: "k8s_ninja",
    role: "DevOps Engineer",
    experience: "Daily Production Driver",
    rating: 5,
    whatLiked: "Visual UI is breathtaking. Seeing live reconciliation status, sync diffs, and pod health in one screen makes debugging effortless.",
    gotchas: "Make sure your Git repo permissions and branch protections are rock solid since Git directly controls production.",
    comment: "Eliminated the need to give our GitLab CI runner admin credentials to production clusters. Security and developer experience both won big.",
    upvotes: 49,
    createdAt: "2026-08-10T11:05:00.000Z"
  },
  {
    productId: "prometheus",
    author: "metrics_guru",
    role: "Senior Observability Engineer",
    experience: "Daily Production Driver",
    rating: 5,
    whatLiked: "PromQL is insanely powerful. Writing rate() and histogram_quantile() queries for 99th percentile response time is second to none.",
    gotchas: "Watch out for high cardinality metrics! Too many dynamic labels (like user IDs) will balloon memory usage.",
    comment: "The bedrock of modern monitoring. Combined with Alertmanager and Grafana, it catches incidents before customers even notice.",
    upvotes: 39,
    createdAt: "2026-08-14T13:45:00.000Z"
  },
  {
    productId: "grafana",
    author: "dashboard_dan",
    role: "SRE Lead",
    experience: "Daily Production Driver",
    rating: 5,
    whatLiked: "Connecting Prometheus, Loki, and PostgreSQL in a single dashboard screen is phenomenal for incident triage.",
    gotchas: "Provision dashboards via code (GitOps) so changes don't get overwritten by accidental manual edits.",
    comment: "Our engineering operations center runs entirely on Grafana wallboards. High polish, fast rendering, and infinite customization.",
    upvotes: 27,
    createdAt: "2026-08-22T08:10:00.000Z"
  },
  {
    productId: "cilium",
    author: "ebpf_elena",
    role: "Cloud Infrastructure Architect",
    experience: "Used in Production (2+ yrs)",
    rating: 5,
    whatLiked: "eBPF speed is unreal. Completely removed iptables latency spikes on our 500-node Kubernetes cluster.",
    gotchas: "Requires modern Linux kernel (5.4+) to unlock all advanced eBPF features.",
    comment: "Hubble's network flow visualization alone justified the switch. We can pinpoint dropped packets and DNS latency in seconds.",
    upvotes: 33,
    createdAt: "2026-08-25T15:55:00.000Z"
  },
  {
    productId: "vault",
    author: "secops_vikram",
    role: "Head of Security & Compliance",
    experience: "Daily Production Driver",
    rating: 5,
    whatLiked: "Dynamic database credentials with 1-hour leases ended the risk of leaked permanent passwords forever.",
    gotchas: "Plan your unsealing strategy carefully (use cloud auto-unseal with AWS KMS or Azure Key Vault).",
    comment: "Vault passed our SOC-2 and ISO-27001 audits with flying colors. It is the gold standard of secrets governance.",
    upvotes: 45,
    createdAt: "2026-08-28T12:00:00.000Z"
  },
  {
    productId: "crossplane",
    author: "platform_leo",
    role: "Internal Developer Platform Lead",
    experience: "Used in Production (1+ yr)",
    rating: 4,
    whatLiked: "Developers can request managed Postgres databases using familiar kubectl commands without knowing AWS IAM intricacies.",
    gotchas: "Debugging deep composition errors can take time when first authoring XRD schemas.",
    comment: "Crossplane turned Kubernetes into our company's private cloud control plane. Total game changer for self-service platform engineering.",
    upvotes: 22,
    createdAt: "2026-09-02T17:15:00.000Z"
  },
  {
    productId: "backstage",
    author: "eng_director_zoe",
    role: "Director of Platform Engineering",
    experience: "Used in Production (2+ yrs)",
    rating: 4,
    whatLiked: "Software Catalog and Golden Path templates cut our microservice creation and onboarding time from weeks to 15 minutes.",
    gotchas: "It is a framework, not an out-of-the-box product. You need a dedicated TypeScript engineer to build and maintain custom plugins.",
    comment: "Solved our 200-engineer company's microservice fragmentation. TechDocs is beloved by all developers.",
    upvotes: 38,
    createdAt: "2026-09-05T10:45:00.000Z"
  },
  {
    productId: "trivy",
    author: "ci_devops_chloe",
    role: "Senior CI/CD Specialist",
    experience: "Daily Production Driver",
    rating: 5,
    whatLiked: "Blazing fast. Scans our production Docker images in 3 seconds directly inside GitHub Actions without setting up any servers.",
    gotchas: "Set vulnerability severity thresholds wisely (e.g. break build only on CRITICAL with fixes available) to avoid developer alert fatigue.",
    comment: "The most developer-friendly security scanner we have ever used. Highly recommend!",
    upvotes: 29,
    createdAt: "2026-09-07T14:10:00.000Z"
  },
  {
    productId: "k9s",
    author: "cluster_operator_ken",
    role: "Kubernetes Administrator",
    experience: "Daily Production Driver",
    rating: 5,
    whatLiked: "I haven't typed a manual kubectl command in two years. The speed of keyboard navigation and log tailing is unmatched.",
    gotchas: "Once you get used to it, you can't go back to normal terminals.",
    comment: "Every DevOps engineer should install K9s on day one. It makes managing clusters fun, fast, and stress-free.",
    upvotes: 56,
    createdAt: "2026-09-10T16:30:00.000Z"
  }
];

module.exports = {
  TOOLS,
  SEED_REVIEWS
};
